trigger:
- main
- release

# trigger this pipeline if there's a PR to any of these branches
pr:
- main
- release/**

variables:
- name: jobTimeout
  value: '60'

# For the latest available agents see:
# https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml&&WT.mc_id=DT-MVP-5002924
- name: windowsAgent
  value: 'windows-latest'

stages:
  - stage: tests
    displayName: Tests
    jobs:
      - template: build/jobs/smoke-test.yml
